import uiscriptlocale

window = {
	"name" : "SelectDialog",
	"style" : ("movable", "float",),
	"x" : 0,
	"y" : 0,
	"width" : 700,
	"height" : 372,
	"children" :
	(
		{
			"name" : "Board",
			"type" : "board",
			"style" : ("attach",),
			"x" : 0,
			"y" : 0,
			"width" : 700,
			"height" : 372,
			"children" :
			(
				{
					"name" : "TitleBar",
					"type" : "titlebar",
					"style" : ("attach",),
					"x" : 8,
					"y" : 10,
					"width" : 700-18,
					"children" :
					(
						{
							"name" : "TitleName",
							"type" : "text",
							"text" : uiscriptlocale.SKILL_SELECT_1,
							"horizontal_align" : "center",
							"text_horizontal_align" : "center",
							"x" : 0,
							"y" : 3,
						},
					),
				},
				{
					"name" : "left_skill_slot_back",
					"type" : "grid_table",
					"x" : 32,
					"y" : 46,
					"start_index" : 0,
					"x_count" : 6,
					"y_count" : 1,
					"x_step" : 40,
					"y_step" : 40,
					"x_blank" : 10,
					"y_blank" : 1,
					"image" : "d:/ymir work/ui/doctrinechoose/slot.tga",
				},
				{
					"name" : "left_skill_slot",
					"type" : "grid_table",
					"x" : 36,
					"y" : 50,
					"start_index" : 0,
					"x_count" : 6,
					"y_count" : 1,
					"x_step" : 40,
					"y_step" : 40,
					"x_blank" : 10,
					"y_blank" : 1,
				},
				{
					"name" : "right_skill_slot_back",
					"type" : "grid_table",
					"x" : 385,
					"y" : 46,
					"start_index" : 0,
					"x_count" : 6,
					"y_count" : 1,
					"x_step" : 40,
					"y_step" : 40,
					"x_blank" : 10,
					"y_blank" : 1,
					"image" : "d:/ymir work/ui/doctrinechoose/slot.tga",
				},
				{
					"name" : "right_skill_slot",
					"type" : "grid_table",
					"x" : 389,
					"y" : 50,
					"start_index" : 0,
					"x_count" : 6,
					"y_count" : 1,
					"x_step" : 40,
					"y_step" : 40,
					"x_blank" : 10,
					"y_blank" : 1,
				},
				{
					"name" : "left_button",
					"type" : "radio_button",
					"x" : 80,
					"y" : 100,
					"default_image" : "d:/ymir work/ui/doctrinechoose/select_job/0/left_normal.tga",
					"over_image" : "d:/ymir work/ui/doctrinechoose/select_job/0/left_hover.tga",
					"down_image" : "d:/ymir work/ui/doctrinechoose/select_job/0/left_down.tga",
					"horizontal_align" : "left",
					"children" :
					(
						{
							"name" : "JobLeftName",
							"type" : "text",
							"text" : "",
							"color" : 0xFFCAA76F,
							"text_horizontal_align" : "center",
							"vertical_align" : "bottom",
							"x" : 100,
							"y" : 24,
						},
					),
				},
				{
					"name" : "right_button",
					"type" : "radio_button",
					"x" : 270,
					"y" : 100,
					"default_image" : "d:/ymir work/ui/doctrinechoose/select_job/0/right_normal.tga",
					"over_image" : "d:/ymir work/ui/doctrinechoose/select_job/0/right_hover.tga",
					"down_image" : "d:/ymir work/ui/doctrinechoose/select_job/0/right_down.tga",
					"horizontal_align" : "right",
					"children" :
					(
						{
							"name" : "JobRightName",
							"type" : "text",
							"text" : "",
							"color" : 0xFFCAA76F,
							"text_horizontal_align" : "center",
							"vertical_align" : "bottom",
							"x" : 100,
							"y" : 24,
						},
					),
				},
				{
					"name" : "left_child_button",
					"type" : "radio_button",
					"x" : 300,
					"y" : 200,
					"default_image" : "d:/ymir work/ui/doctrinechoose/empty_01_normal.tga",
					"over_image" : "d:/ymir work/ui/doctrinechoose/filled_02_hover.tga",
					"down_image" : "d:/ymir work/ui/doctrinechoose/filled_03_active.tga",
					"horizontal_align" : "left",
				},
				
				{
					"name" : "right_child_button",
					"type" : "radio_button",
					"x" : 310,
					"y" : 200,
					"default_image" : "d:/ymir work/ui/doctrinechoose/empty_01_normal.tga",
					"over_image" : "d:/ymir work/ui/doctrinechoose/filled_02_hover.tga",
					"down_image" : "d:/ymir work/ui/doctrinechoose/filled_03_active.tga",
					"horizontal_align" : "right",
				},
				{
					"name" : "SelectButton",
					"type" : "button",
					"x" : (700 / 2) - (218 / 2),
					"y" : 330,
					"default_image" : "d:/ymir work/ui/doctrinechoose/select_normal.tga",
					"over_image" : "d:/ymir work/ui/doctrinechoose/select_hover.tga",
					"down_image" : "d:/ymir work/ui/doctrinechoose/select_down.tga",
					"text" : uiscriptlocale.SKILL_SELECT_2,
				},
			),
		},
	),
}

