import app
import localeinfo

BOARD_WIDTH = 465
BOARD_HEIGHT = 274

window = {
	"name" : "BiologWindow",
	"x" : 0,
	"y" : 0,
	"style" : ("movable", "float",),
	"width" : BOARD_WIDTH,
	"height" : BOARD_HEIGHT,
	"children" :
	(
		{
			"name" : "board",
			"type" : "board_with_titlebar",
			"style" : ("attach",),
			"x" : 0,
			"y" : 0,
			"width" : BOARD_WIDTH,
			"height" : BOARD_HEIGHT,
			"title" : localeinfo.LOCALIZATION_TITLE,
			"children" :
			(
				{
					"name" : "slot1",
					"type" : "expanded_image",
					"x" : 10,
					"y" : 36,
					"width" : 139,
					"height" : 105,
					"image" : "d:/ymir work/ui/game/savepoint/background.tga",
					"children" : (
						{
							"name" : "map1",
							"type" : "text",
							"x" : 0,
							"y" : -40,
							"text" : "",
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "status1",
							"type" : "text",
							"x" : 0,
							"y" : -20,
							"text" : localeinfo.SAVEPOINT_EMPTY,
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "coordinates1",
							"type" : "text",
							"x" : 0,
							"y" : 0,
							"text" : "",
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "save_btn1",
							"type" : "button",
							"x" : 0,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_save_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_save_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_save_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_SAVE,
						},
						{
							"name" : "delete_btn1",
							"type" : "button",
							"x" : -40,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_delete_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_delete_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_delete_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_EMPTYIT,
						},
						{
							"name" : "go_btn1",
							"type" : "button",
							"x" : 40,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_go_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_go_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_go_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_GO,
						},
					),
				},
				{
					"name" : "slot2",
					"type" : "expanded_image",
					"x" : 163,
					"y" : 36,
					"width" : 139,
					"height" : 105,
					"image" : "d:/ymir work/ui/game/savepoint/background.tga",
					"children" : (
						{
							"name" : "map2",
							"type" : "text",
							"x" : 0,
							"y" : -40,
							"text" : "",
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "status2",
							"type" : "text",
							"x" : 0,
							"y" : -20,
							"text" : localeinfo.SAVEPOINT_EMPTY,
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "coordinates2",
							"type" : "text",
							"x" : 0,
							"y" : 0,
							"text" : "",
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "save_btn2",
							"type" : "button",
							"x" : 0,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_save_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_save_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_save_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_SAVE,
						},
						{
							"name" : "delete_btn2",
							"type" : "button",
							"x" : -40,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_delete_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_delete_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_delete_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_EMPTYIT,
						},
						{
							"name" : "go_btn2",
							"type" : "button",
							"x" : 40,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_go_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_go_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_go_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_GO,
						},
					),
				},
				{
					"name" : "slot3",
					"type" : "expanded_image",
					"x" : 316,
					"y" : 36,
					"width" : 139,
					"height" : 105,
					"image" : "d:/ymir work/ui/game/savepoint/background.tga",
					"children" : (
						{
							"name" : "map3",
							"type" : "text",
							"x" : 0,
							"y" : -40,
							"text" : "",
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "status3",
							"type" : "text",
							"x" : 0,
							"y" : -20,
							"text" : localeinfo.SAVEPOINT_EMPTY,
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "coordinates3",
							"type" : "text",
							"x" : 0,
							"y" : 0,
							"text" : "",
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "save_btn3",
							"type" : "button",
							"x" : 0,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_save_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_save_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_save_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_SAVE,
						},
						{
							"name" : "delete_btn3",
							"type" : "button",
							"x" : -40,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_delete_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_delete_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_delete_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_EMPTYIT,
						},
						{
							"name" : "go_btn3",
							"type" : "button",
							"x" : 40,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_go_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_go_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_go_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_GO,
						},
					),
				},
				{
					"name" : "slot4",
					"type" : "expanded_image",
					"x" : 10,
					"y" : 155,
					"width" : 139,
					"height" : 105,
					"image" : "d:/ymir work/ui/game/savepoint/background.tga",
					"children" : (
						{
							"name" : "map4",
							"type" : "text",
							"x" : 0,
							"y" : -40,
							"text" : "",
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "status4",
							"type" : "text",
							"x" : 0,
							"y" : -20,
							"text" : localeinfo.SAVEPOINT_EMPTY,
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "coordinates4",
							"type" : "text",
							"x" : 0,
							"y" : 0,
							"text" : "",
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "save_btn4",
							"type" : "button",
							"x" : 0,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_save_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_save_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_save_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_SAVE,
						},
						{
							"name" : "delete_btn4",
							"type" : "button",
							"x" : -40,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_delete_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_delete_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_delete_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_EMPTYIT,
						},
						{
							"name" : "go_btn4",
							"type" : "button",
							"x" : 40,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_go_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_go_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_go_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_GO,
						},
					),
				},
				{
					"name" : "slot5",
					"type" : "expanded_image",
					"x" : 163,
					"y" : 155,
					"width" : 139,
					"height" : 105,
					"image" : "d:/ymir work/ui/game/savepoint/background.tga",
					"children" : (
						{
							"name" : "map5",
							"type" : "text",
							"x" : 0,
							"y" : -40,
							"text" : "",
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "status5",
							"type" : "text",
							"x" : 0,
							"y" : -20,
							"text" : localeinfo.SAVEPOINT_EMPTY,
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "coordinates5",
							"type" : "text",
							"x" : 0,
							"y" : 0,
							"text" : "",
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "save_btn5",
							"type" : "button",
							"x" : 0,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_save_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_save_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_save_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_SAVE,
						},
						{
							"name" : "delete_btn5",
							"type" : "button",
							"x" : -40,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_delete_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_delete_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_delete_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_EMPTYIT,
						},
						{
							"name" : "go_btn5",
							"type" : "button",
							"x" : 40,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_go_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_go_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_go_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_GO,
						},
					),
				},
				{
					"name" : "slot6",
					"type" : "expanded_image",
					"x" : 316,
					"y" : 155,
					"width" : 139,
					"height" : 105,
					"image" : "d:/ymir work/ui/game/savepoint/background.tga",
					"children" : (
						{
							"name" : "map6",
							"type" : "text",
							"x" : 0,
							"y" : -40,
							"text" : "",
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "status6",
							"type" : "text",
							"x" : 0,
							"y" : -20,
							"text" : localeinfo.SAVEPOINT_EMPTY,
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "coordinates6",
							"type" : "text",
							"x" : 0,
							"y" : 0,
							"text" : "",
							"fontname" : "Tahoma:18b",
							"all_align" : "center",
							"color" : 0xFFDBB06E,
						},
						{
							"name" : "save_btn6",
							"type" : "button",
							"x" : 0,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_save_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_save_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_save_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_SAVE,
						},
						{
							"name" : "delete_btn6",
							"type" : "button",
							"x" : -40,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_delete_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_delete_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_delete_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_EMPTYIT,
						},
						{
							"name" : "go_btn6",
							"type" : "button",
							"x" : 40,
							"y" : 36,
							"horizontal_align" : "center",
							"vertical_align" : "bottom",
							"default_image" : "d:/ymir work/ui/game/savepoint/btn_go_normal.tga",
							"over_image" : "d:/ymir work/ui/game/savepoint/btn_go_over.tga",
							"down_image" : "d:/ymir work/ui/game/savepoint/btn_go_down.tga",
							"tooltip_text" : localeinfo.SAVEPOINT_GO,
						},
					),
				},
			),
		},
	),
}
