#ifndef __INC_PYTHON_rootlib_MANAGER_H__
#define __INC_PYTHON_rootlib_MANAGER_H__
#define initrootlibManager initrootlib
/* rootlib module */
/* rootlib.isExist */
/* rootlib.moduleImport */
/* rootlib.getList */
/* this lib includes modules under this lines.
	colorinfo
	consolemodule
	constinfo
	dailygift
	debuginfo
	dragon_soul_refine_settings
	emotion
	exception
	game
	ingamewiki
	ingamewikiconfig
	ingamewikiui
	interfacemodule
	introcreate
	introempire
	introloading
	intrologin
	introselect
	localeinfo
	marek38
	mousemodule
	musicinfo
	networkmodule
	playersettingmodule
	prototype
	servercommandparser
	serverinfo
	stringcommander
	system
	test_affect
	ui
	uiacce
	uiaffectshower
	uiattachmetin
	uiattrdialog
	uiattrtransfer
	uiauction
	uiautoban
	uibattlepass
	uibiolog
	uicandidate
	uichannel
	uicharacter
	uicharacterdetails
	uichat
	uicommon
	uicube
	uicuberenewal
	uidoctrinechoose
	uidragonlairranking
	uidragonsoul
	uiduel
	uidungeoninfo
	uiequipmentdialog
	uiex
	uiexchange
	uiextrainventory
	uifishing
	uigamebutton
	uigameoption
	uiguild
	uiguildrank
	uiinventory
	uimapnameshower
	uimarketsystem
	uimessenger
	uiminimap
	uiofflineshop
	uioption
	uiparty
	uipetenchant
	uipetevownd
	uipetfeed
	uipetincubatrice
	uipetsystem
	uiphasecurtain
	uipickmoney
	uiplayergauge
	uipointreset
	uiprivateshopbuilder
	uiquest
	uiranking
	uirefine
	uirestart
	uirune
	uisafebox
	uisavepoint
	uiscriptlocale
	uiselectitem
	uiselectmusic
	uishop
	uiskillcolor
	uiswitchbot
	uisystem
	uisystemgems
	uisystemoption
	uitarget
	uitaskbar
	uiteleporter
	uitip
	uitooltip
	uiuploadmark
	uiweb
	uiwheel
	uiwhisper
	utils
	whispermanager
*/
void initrootlibManager();
#endif
